[General]
    # TriggerIntervalSec represents the trigger interval for the main cron job
    TriggerIntervalSec = 5

[Alarms]
    [Alarms.NodeRating]
        # Threshold defines the percentage change limit in case node temprating is decreasing
        Threshold = 1.0 # percentage change limit

        # PubKeys defines the list of public keys (BLS keys) to be check from api
        PubKeys = [
        ]

[Notifiers]
    [Notifiers.Email]
        # Enabled specifies wether the email notifier will be enabled or not
        Enabled = true
        
        # EmailHost represents the smtp host (like smtp.gmail.com)
        EmailHost = ""

        # EmailPort represents the smtp host port
        EmailPort = 587

        # EmailUsername specifies the email address (like aaa.bbb@mail.com)
        EmailUsername = ""

        # EmailPassword specifies password for provided email address
        EmailPassword = ""  

        # From defines the email address to be listed as from in email (can be the same as EmailUsername)
        From = ""

        # To represents the list of email addresses to send to
        To = [
        ]
